### ISSUE TITLE
Titel der Zusammenfassung für Endliche Automaten ist falsch

### ISSUE THREAD

**Issue by grohjann** [felix-vierthaler/Grundbegriffe-der-Informatik-wiki#1]
Der Titel von der Seite für die Endlichen Automaten heißt "Graphen Zusammenfassung", sollte aber wahrscheinlich ehr "Endliche Automaten Zusammenfassung" heißen

**Comment by felix-vierthaler** [comment]
Super danke! wird gefixt.
